### ISSUE TITLE
您好，可以提供一下有正负情感标签的数据集吗？我想作为硕士毕业论文的实验数据使用，非常感谢！🙏

### ISSUE THREAD

**Issue by wildalmond** [nwulq/corpus#1]

**Comment by nwulq** [comment]
你好，请问是英文的数据集么？


 
---原始邮件---
发件人: "wildalmond"<notifications@github.com&gt;
发送时间: 2020年10月23日(星期五) 下午3:23
收件人: "jiaoyuanluqiang/corpus"<corpus@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [jiaoyuanluqiang/corpus] 您好，可以提供一下有正负情感标签的数据集吗？我想作为硕士毕业论文的实验数据使用，非常感谢！🙏 (#1)

**Comment by wildalmond** [comment]
> 你好，请问是英文的数据集么？
> […](#)
> ---原始邮件--- 发件人: "wildalmond"🙏 (#1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是有标签的清华大学中文宾馆评论语料库 感谢~

**Comment by nwulq** [comment]
github上的数据库是分为2部分，前一部分是积极的，后一部分是消极的，因为处理好的数据不在我这里，所以只能提供未标签的数据，您可以尝试自己进行标注------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wildalmond&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月23日(星期五) 晚上7:34
收件人:&nbsp;&quot;jiaoyuanluqiang/corpus&quot;<corpus@noreply.github.com&gt;;
抄送:&nbsp;&quot;IU&quot;<942076812@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jiaoyuanluqiang/corpus] 您好，可以提供一下有正负情感标签的数据集吗？我想作为硕士毕业论文的实验数据使用，非常感谢！🙏 (#1)
